#!/bin/bash
# Is not so advanced but hopefully it works

if [ -z "$(echo "$1" | grep -E '^(http[s]?|ftp)://')" ]
then
    /bin/xdg-open "$1"
else
    if [ ! -z "$(echo "$1" | grep '\.pdf$')" ]
    then
	curl "$1" | zathura -
    elif [ ! -z "$(echo "$1" | grep -E '\.(jpeg|png|jpg)$')" ]
    then
	feh "$1"
    else
	/bin/xdg-open "$1"
    fi
fi
