#!/bin/bash

if [ "x$1" != "x" ]; then
    cd $1 2> /dev/null
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

FILE="$(ls *.tex | xargs -n1 grep -H '\\begin{document}' | cut -d':' -f1)"

if [ $(echo "$FILE" | wc -l) -ne 1 ]; then
    >&2 echo "$(echo "$FILE" | wc -l) different main tex files found"
    exit 1
fi
FILE=$(echo "$FILE" | sed 's/\.tex$//')

xdg-open $FILE.pdf 2>/dev/null&
vim $FILE.tex
exit 0
