#!/bin/bash

if [ "x$1" != "x" ]; then
    cd $1 2> /dev/null
    if [ $? -ne 0 ]; then
	exit 1
    fi
fi

FILE=$(ls *.latexmain 2> /dev/null | sed 's/\.tex\.latexmain//')

if [ "x$FILE" == "x" ]; then
    if [ $(ls *.tex 2> /dev/null | wc -l) -eq 0 ]; then
	(>&2 echo "No tex file found.")
	exit 1
    elif [ $(ls *.tex 2> /dev/null | wc -l) -ne 1 ]; then
	(>&2 echo "More than one tex file found, touch a .latexmain file.")
	exit $(echo $FILE | wc -l)
    fi
    FILE=$(ls *.tex 2> /dev/null | sed 's/\.tex//')
fi

xdg-open $FILE.pdf 2>/dev/null&
vim $FILE.tex
exit 0
